/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 17.11.2025 14:21:01

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 5536;
#else
constexpr int kTensorArenaSize = 4512;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,1568 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 49, 32, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 49, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 416, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { -1676, 3670, 83, -2434, };
const TfArray<1, float> quant6_scale = { 1, { 3.5764627682510763e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*416] = { 
  41, 52, -27, 15, 2, -4, 18, -54, 21, -21, -39, -16, -27, -2, 13, -17, 37, 45, 13, -47, -5, 0, -71, 14, -29, 17, 15, 68, -61, 10, -5, -44, 24, 48, -83, 9, 11, 45, 40, -57, -20, -73, -55, -45, 13, -120, 39, 3, 58, 47, 57, -81, -32, 23, -100, 24, -79, -28, -12, 40, -44, -12, 51, 3, 38, 4, -94, 29, 21, 44, 40, -60, -30, -37, -51, -33, -54, -107, 22, 13, 16, 46, -6, -30, -10, 9, -26, 15, -23, 29, 8, 83, -24, -49, 15, -61, 10, 21, -27, 44, 13, 61, 52, -60, -46, -27, -81, -34, -18, -45, 25, 46, 39, 33, -49, -27, 7, 45, -26, -19, 27, 24, 5, 12, -23, -5, 9, -12, -6, 20, -56, -17, -1, 2, 33, 2, 13, 4, -39, -3, -15, -97, 0, 34, 63, 5, 7, -6, -38, 51, -38, -18, 3, 34, -28, -26, -24, -40, 51, 17, -14, 26, -14, 58, 13, 43, 28, -45, -36, 10, -17, -8, -8, -81, 36, 29, 79, 28, 9, -56, -15, 38, -84, 39, -20, 17, -27, -27, -1, 36, 16, -35, 11, -21, -23, -2, -46, 9, 5, -24, -15, 6, -76, -34, -35, 15, 23, 13, 17, 3, 13, 1, 19, 40, -46, 3, -56, -16, -35, -15, -44, -13, 19, -54, 30, 5, -73, -9, -18, 38, -12, -61, -37, -19, -60, -6, -42, -38, -23, 39, 55, 58, 64, -2, -10, 9, -52, 32, -36, 20, -64, 41, -58, -37, -1, -54, 13, -23, -30, 20, 52, 58, -29, -40, -37, -5, -20, 17, 15, -68, 15, 28, 64, 54, 36, -63, -44, 9, -33, 35, -48, 13, -9, 4, -58, -53, 43, -36, -18, 41, -53, 4, -7, 33, 11, -47, -3, -17, -71, -9, 5, -78, -16, 34, 24, 18, 0, 9, -25, 42, -11, 49, 27, -25, -10, -22, -46, -13, -12, 6, 48, -50, -43, 11, 13, 52, 47, 1, -16, -17, -32, -48, -3, -58, 7, -1, -1, 34, 71, 9, -14, 8, -58, 9, -40, 4, -47, 34, 10, 11, 57, -17, 57, 30, -65, 54, 27, 54, 67, -41, 25, -43, -10, -63, -9, -87, -30, 31, 52, 54, 26, -10, -36, 29, -84, 58, -17, -21, -79, -20, -37, 18, 27, -19, -41, 51, 20, 52, 0, -8, 21, -28, 32, -34, -32, -13, 18, -63, -23, 60, 49, 99, -52, -39, -62, 16, -19, 54, -38, 33, -80, 18, -43, -42, 24, 9, 
  -62, -1, -7, -24, -48, -47, -51, -3, -80, 18, 6, 31, 21, -81, -58, -37, -1, -2, -126, 49, -60, -4, 36, -32, 50, 15, -10, -7, 38, 40, 19, -59, -34, -18, 34, -23, -12, -56, -78, -17, -73, 32, -35, 56, -15, -86, -100, -72, -2, -13, -63, 49, -70, -16, 13, -16, 41, 38, 19, 11, 7, 14, 33, -3, -85, -5, 57, 21, -53, -55, -1, -23, -72, -8, 13, 4, 47, -68, -79, -69, -35, -61, -89, 32, -72, -20, -3, 34, 48, 41, -17, -51, 7, 14, 16, -41, -57, 26, 38, -34, -14, -36, -35, -7, -40, 33, -10, 14, -12, -101, -33, -48, -17, -62, -59, 43, -45, -26, 25, -7, 9, 29, 41, 54, 39, 2, -2, -50, -33, 40, 10, -6, 2, -64, 10, -26, -55, 8, 2, 21, 4, -105, -44, -37, -23, -43, -28, 47, -12, 25, 18, 18, 4, 4, 8, 69, 48, -12, 52, -17, -6, 27, 20, -44, -36, -52, -12, 29, -69, 5, 11, 31, 8, -92, -10, -69, -42, -18, -80, 27, -39, 27, 37, -10, 27, 28, -14, 39, 70, 37, -37, -4, -31, 21, 57, -63, 32, -26, -31, 16, -47, -22, -41, 46, -2, -74, -58, -16, -28, -69, -67, 6, -75, 1, 5, 4, 32, 30, -14, -28, 9, 32, 13, -39, -69, 14, 40, -2, -7, -34, -22, 18, -24, 36, 0, -7, -22, -92, -57, -48, -23, -10, -52, 27, -56, 28, 39, 31, -30, -8, -5, -17, 40, 5, 56, -42, -54, 48, 20, -44, -11, -88, 0, -25, -58, 24, -35, 54, 26, -46, -86, -65, -30, -70, -23, 39, -61, 28, 43, -14, 25, 31, 20, 38, 62, -8, 40, -19, -60, 17, 22, -32, -49, -80, -27, 27, -75, 16, -19, 53, -28, -32, -81, 0, -62, -58, -31, 28, -84, -3, 52, 6, -18, 30, 11, -3, 75, 31, 15, -43, -87, 40, 8, -4, -29, -10, -64, 3, -49, 22, 4, 29, -43, -78, -54, -75, -53, -50, -24, -10, -39, -46, 18, -13, 20, 24, 26, 57, 37, -31, -8, 4, -55, 3, 38, -18, -34, -25, -58, 46, -46, 1, -7, 13, -11, -114, -55, -62, -6, -79, -82, 18, -46, -55, 37, 14, 20, 21, 5, 34, 10, 15, -22, -20, -6, 40, 18, -40, 18, 25, -32, 35, -4, 4, 15, 43, 14, -58, -22, -3, -30, -21, -8, -5, -21, 23, -14, -15, -4, -17, 47, 24, 30, 20, 0, 26, 
  10, -1, -51, -84, 87, -9, 58, 58, 34, -86, 40, 60, -63, 83, 51, 85, 31, 0, 20, 11, 56, -52, 43, -80, -55, -114, 21, 21, -1, -29, -60, 23, -17, 9, -6, -1, 57, -13, 21, 64, 27, -74, 22, 62, -79, 96, 15, 25, 25, 28, 56, -30, 34, -58, 18, -90, 5, -45, 66, -127, 4, -35, -72, -36, 27, 5, -33, -29, 51, 44, 64, 17, -5, -34, 47, 25, -55, 36, 56, 38, 4, -10, 27, -13, -1, -72, 54, -69, -57, -52, 57, -69, -19, -86, -17, -48, 23, -35, -30, 13, 26, -33, -5, 62, 17, -16, 12, 15, -64, 32, 53, 16, 32, 11, 36, -17, 36, -84, 46, -7, -7, -88, 32, -71, 14, -78, -41, -11, 19, -30, -5, -44, 53, 46, 28, -8, -8, -67, -10, 20, -82, 47, 23, 51, 22, -26, -6, 15, 8, -10, 33, -31, -6, -62, 54, -40, -3, -70, -55, -23, -43, -37, -16, -5, 56, 59, 41, 48, 10, -26, 43, -21, -34, 21, 50, 9, 33, 3, -32, -55, 15, -80, 58, -26, -48, -30, 61, -54, 42, -45, -42, -50, -14, 35, -28, 25, 40, 34, 13, 53, 41, -34, 16, 32, -34, 52, 26, -1, 32, -11, -14, -36, 27, -63, -5, -61, -17, -15, -5, -30, -10, -30, -58, -14, -28, -48, 4, 10, 58, 64, -13, -11, 33, -54, 52, 1, 6, 36, 22, 62, -3, 26, 42, -14, 9, -42, 29, -22, -31, -13, 33, -49, 24, -54, -69, 23, 37, 34, -49, -35, 63, 70, 56, 11, 45, -60, 16, 35, -22, 32, 8, 32, -1, 34, 38, 0, 44, -32, 51, -29, -39, -57, 46, -78, 18, -47, -37, 3, -25, 13, -40, -17, 19, -16, -3, 12, -8, -26, -17, 3, -73, 4, -11, 21, -16, 21, 26, -71, 42, -70, 43, -35, -26, -41, 34, -23, 42, -22, -73, 12, 7, -13, 2, -42, 59, 3, 29, 54, 18, -29, -3, 6, -54, 54, 7, 19, -9, 30, 36, -31, 22, -72, 32, -43, -65, -53, 26, -62, 31, -33, -12, 12, -3, -3, -27, 11, 24, -29, 46, 50, 46, -93, -35, 51, -85, 77, -25, 45, -14, -17, 20, -15, 8, -97, 9, -84, -15, -84, 24, 28, 31, -64, -46, -25, -32, 5, -38, -26, 32, -1, -56, 24, -55, -71, -11, -11, -20, 31, -14, -53, 2, -8, 3, -81, -44, -53, 23, -22, -33, -37, -31, -77, -10, -43, -85, -61, 
  25, -19, 21, 5, -45, -50, 2, -6, 33, -6, 32, -61, -5, 17, 69, 16, -34, -82, -11, 58, 58, -23, -2, 17, 11, -7, -43, -102, -105, 42, -31, 5, 37, -36, 9, -44, -44, -72, -27, -20, 32, 34, 11, -78, 26, 47, 16, -2, -22, -33, 3, 48, 76, -9, -16, 13, 20, 14, -63, -79, -86, 13, -60, 37, 8, -30, 58, -30, -71, -14, -52, 27, 33, 46, 54, -53, -8, 66, 15, -67, -55, -12, -4, 52, 76, 16, -63, 11, 37, 13, -54, -69, -89, 27, -48, 3, 14, -44, 9, -33, -78, -30, -65, -28, 51, 44, 47, -62, 38, 51, 52, -3, -33, -41, -13, 1, 21, -34, -45, -8, -15, -8, -23, -40, -11, 12, -10, -6, 39, -8, 19, 18, -63, -2, 1, -18, 70, 48, 47, -56, 39, 57, 32, 10, 15, -14, 36, 25, 29, 42, -3, 22, -6, -24, -12, -63, -84, -12, -34, -6, -11, -43, 18, -15, -57, -48, -18, -17, 32, 11, 8, -52, 39, 4, 53, -7, 19, -9, 62, 18, 60, 26, -49, -9, 23, -21, -48, 44, -21, 47, -37, 48, 20, -56, 18, -36, -40, -6, -13, -17, 47, 11, 31, -80, -13, 16, -11, -46, -38, -40, -3, 13, 9, 10, -55, 31, -1, 36, -62, -77, -61, 33, -36, 39, -12, 39, 0, 13, -74, -60, 4, 21, 13, 44, 63, -52, -10, 31, -11, 13, -46, -33, -45, 34, 37, 17, -54, -17, -20, 4, -32, 0, -12, 33, -19, 24, 10, -19, -3, -4, -81, -43, -12, 50, 12, 48, 18, -57, 10, 31, -3, -57, -43, -62, -10, -10, 50, 23, -43, 40, -25, 15, -20, -82, 6, 15, 2, 54, 21, -64, 26, -45, -49, -44, -19, -11, 36, 18, 64, -46, 9, 43, 58, -36, -5, -16, 20, 5, -3, 13, -39, 47, -1, -16, -30, -4, -43, -14, 9, 55, 3, -43, 8, -33, -48, -6, -28, -6, 2, 31, 44, -77, 6, 45, -23, -9, -10, -9, 4, -1, -6, -8, -16, 37, -25, 0, -25, -32, -49, 17, -41, 37, -11, -36, 19, -32, -48, -4, 8, 41, 65, 46, 44, -79, 8, 47, 6, -19, -37, 32, 16, 30, 20, -10, -34, 0, 22, 24, -52, 8, -19, 32, 23, 25, 35, -34, -19, 9, -60, -43, -50, 10, 10, 29, 3, -15, 27, 8, 42, -18, -34, -10, -2, 40, 54, 31, 35, -22, 0, -14, 31, -2, -3, 1, -13, 25, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,416 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0029302837792783976, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[32] = { -1724, 3852, 6327, -1714, 1582, 281, 64, 2830, -4971, 4399, -1983, 7242, 1456, -6259, -2835, -1031, 811, -1384, -1367, 6137, -5449, -3527, 5120, -3210, 5498, 4518, 4233, -757, 6813, 3091, -883, -4124, };
const TfArray<1, int> tensor_dimension8 = { 1, { 32 } };
const TfArray<32, float> quant8_scale = { 32, { 2.3661252271267585e-05, 2.4049097191891633e-05, 2.0399258573888801e-05, 2.2268590328167193e-05, 2.9267601348692551e-05, 2.8681446565315127e-05, 1.6227311789407395e-05, 1.8085196643369272e-05, 2.186960045946762e-05, 1.7942567865247838e-05, 2.1493735403055325e-05, 2.1649126210832037e-05, 1.7284977730014361e-05, 2.2718910258845426e-05, 3.0172033802955411e-05, 2.5130100766546093e-05, 2.4484390451107174e-05, 2.3732896806905046e-05, 2.7691983632394113e-05, 1.9162485841661692e-05, 2.0417044652276672e-05, 2.3726352083031088e-05, 2.1978483346174471e-05, 2.1767284124507569e-05, 2.0819754354306497e-05, 1.9268847609055229e-05, 2.2326337784761563e-05, 2.7957294150837697e-05, 2.3386215616483241e-05, 2.3902986868051812e-05, 2.0730465621454641e-05, 1.8988996089319699e-05, } };
const TfArray<32, int> quant8_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[32*1*3*16] = { 
  /* [0][0][][] */ 44,127,-15,15,11,-4,-17,61,92,21,-43,81,79,121,33,-7, -29,74,-46,68,0,45,103,36,-30,-47,-25,71,73,32,-66,-28, 77,94,-4,61,45,-61,31,21,112,-40,25,69,32,-32,22,-15, 
  /* [1][0][][] */ -53,36,-4,-15,-16,-5,68,90,127,40,0,-19,64,-10,-20,41, -27,51,-23,8,72,2,9,-36,-4,70,89,-28,-42,-49,61,12, -84,43,1,-43,-6,56,-90,1,-18,5,-35,-18,44,10,40,-29, 
  /* [2][0][][] */ -35,-73,2,12,84,50,-34,20,-103,29,-57,21,-13,-26,-20,107, -24,-37,60,-47,1,70,-35,-2,-32,-16,-88,-82,-82,89,112,76, 2,-28,-62,-42,72,-9,-127,44,-119,-63,-24,-32,-25,101,107,113, 
  /* [3][0][][] */ 28,40,37,-64,10,-17,65,5,-5,-25,67,35,127,17,-8,-71, -16,-24,-42,-7,-51,73,17,66,83,67,90,27,-7,-55,-51,-29, -55,92,32,19,1,45,78,-41,106,58,-44,-12,-2,21,-63,3, 
  /* [4][0][][] */ -63,-18,-55,24,-53,-46,4,48,23,34,-45,-35,2,14,50,34, -8,6,-78,-54,-40,-24,86,56,-50,-30,5,-1,-2,-26,10,-42, 48,-56,29,-48,-57,37,126,30,-67,47,127,67,69,39,-11,-34, 
  /* [5][0][][] */ -39,53,-20,-30,-43,-4,108,-26,-5,35,40,-17,19,-9,26,-22, -52,32,25,43,15,-3,-16,33,59,-30,-44,-15,46,-19,12,-7, 54,2,-11,-34,10,6,127,0,8,-9,43,96,49,-33,-53,-22, 
  /* [6][0][][] */ 115,60,-93,14,38,80,105,54,16,-35,92,-30,15,55,-76,-86, 124,-70,15,30,19,104,90,117,96,63,-23,-40,125,-42,75,-46, -127,90,-81,13,-5,-56,-26,-15,-67,-101,-82,-115,-36,125,55,-33, 
  /* [7][0][][] */ 15,-59,-86,78,-4,40,95,79,-74,-75,122,75,-17,12,95,52, -39,-14,-50,84,-127,-37,1,21,-112,-1,50,-61,-5,79,115,-21, -23,-28,-78,71,-8,-73,72,1,-52,-22,-44,57,12,122,-11,28, 
  /* [8][0][][] */ 95,40,28,73,-29,-87,73,-105,35,15,0,27,27,127,-39,63, 43,-47,33,-39,-66,-70,54,41,43,16,30,96,82,125,14,-14, 104,-81,23,63,-10,-36,19,-1,-41,-92,-71,118,-12,42,8,-12, 
  /* [9][0][][] */ 87,34,-2,62,-21,-16,-77,-44,5,-46,-33,24,-49,-16,-38,41, 18,57,58,-24,-15,73,-86,30,-84,-39,-20,-14,5,74,-35,-21, 38,-63,101,-15,24,87,-127,-59,-59,-47,-31,-21,8,17,35,123, 
  /* [10][0][][] */ -8,-21,22,52,-78,-41,-31,-74,-47,-66,-77,20,-19,44,14,79, 113,40,-3,70,5,-73,30,-78,16,-66,24,103,-63,127,9,-40, -9,-61,-10,67,-27,-38,46,51,7,-102,-53,67,-64,110,-74,94, 
  /* [11][0][][] */ -109,-97,28,-15,-30,59,101,59,-65,-8,-2,-82,50,10,101,21, -57,-127,-41,-35,-3,8,-34,84,-112,77,103,-67,4,-4,24,-45, -15,-117,-48,32,64,86,114,55,-117,-13,69,-37,-49,-21,74,40, 
  /* [12][0][][] */ -19,-18,-2,55,90,-59,-70,-114,111,41,24,9,-105,-17,3,35, 95,5,51,1,43,69,-61,-26,54,-44,-42,-16,-49,28,-2,24, 127,100,82,-14,116,-24,-88,35,6,-6,-29,70,56,13,-110,6, 
  /* [13][0][][] */ 120,-28,-58,8,2,-51,38,-34,-19,-4,88,20,55,111,58,26, 17,-127,-54,97,-74,-15,78,34,-10,-104,-70,-82,15,118,66,-19, 16,-47,7,27,29,-75,35,-39,-39,-3,-45,54,18,59,23,62, 
  /* [14][0][][] */ 50,73,-5,8,-25,21,39,15,71,-8,20,34,98,37,-41,7, 66,61,41,62,-37,-40,39,-30,31,-8,-14,23,-16,19,35,5, 37,38,3,-5,-31,-53,127,-20,66,-54,-9,2,6,90,17,11, 
  /* [15][0][][] */ 48,21,-8,-31,0,34,99,23,9,41,-18,12,102,12,14,-38, -29,51,-59,12,21,39,59,3,-3,-36,-36,32,65,53,28,-46, 102,82,-58,-49,-28,8,120,64,52,7,127,58,-10,50,2,13, 
  /* [16][0][][] */ 20,89,-7,29,9,0,56,5,80,27,-12,14,111,45,6,-68, 19,28,-4,-51,51,51,127,-14,71,7,87,24,65,-50,8,-54, 18,22,-15,22,-22,-9,5,73,-18,20,62,49,41,-34,-20,-44, 
  /* [17][0][][] */ 55,92,-39,41,-12,13,112,89,72,-58,-42,36,123,-6,-58,-34, 77,66,20,-44,16,-25,127,7,21,-37,78,-6,45,-39,7,-27, -28,46,-30,-38,46,24,37,72,53,22,95,-9,68,-23,-12,18, 
  /* [18][0][][] */ 32,85,7,69,15,15,-45,78,45,-16,-4,2,127,70,34,32, 104,38,3,-35,-25,-13,60,-23,31,25,47,3,76,83,18,8, -43,70,-42,-42,-25,-58,84,9,89,-3,-57,17,18,35,-59,-47, 
  /* [19][0][][] */ -34,-71,11,50,-35,81,-122,-4,-20,-22,-47,56,-92,13,-51,28, -5,-82,64,83,62,61,-107,50,-42,-49,-33,-43,-41,-14,-71,116, 0,-127,-3,47,85,-41,-99,11,-114,-22,42,78,-97,98,93,8, 
  /* [20][0][][] */ 14,-52,-37,45,-42,-77,94,-75,81,-66,84,72,-4,89,24,-22, 127,-28,91,39,-52,-11,1,-1,-13,-23,-54,-39,35,86,-38,86, 96,-45,-15,82,-50,-105,55,6,86,-77,-76,63,-29,84,-5,7, 
  /* [21][0][][] */ 48,83,-49,58,36,-9,50,-45,127,38,-9,65,98,-25,-78,-69, 41,74,45,37,62,74,42,-37,84,42,35,19,48,9,-109,-49, 33,86,38,-45,54,-25,34,-27,18,71,-4,55,67,-58,-116,-79, 
  /* [22][0][][] */ -6,0,-25,19,-52,-49,27,94,-116,61,70,-43,-17,-19,66,-17, -20,-102,23,26,69,-16,54,127,-100,-40,88,-54,-6,-40,68,70, -65,20,-49,-14,-70,-52,-57,33,-91,77,42,-83,-32,17,99,-14, 
  /* [23][0][][] */ 52,-8,80,22,83,74,39,36,96,10,-19,23,127,-78,-93,-3, 94,120,70,-8,29,25,10,4,47,44,-37,112,-39,-3,-56,-17, 19,51,41,16,34,-37,33,-13,94,-35,15,-8,108,-99,-68,-83, 
  /* [24][0][][] */ -64,2,1,33,-22,81,-46,64,-46,43,46,-4,-123,-8,-59,19, 11,-51,69,35,-35,40,-50,15,-127,-29,21,-37,-95,-51,-45,86, 22,-22,-44,-45,-14,-16,-55,-65,-39,67,23,-37,-18,35,-40,67, 
  /* [25][0][][] */ -92,68,62,12,35,8,5,23,1,127,37,54,52,-120,59,54, -83,-60,23,-59,108,75,9,-67,89,30,20,2,-67,-77,19,65, -6,-5,82,-20,82,-22,-49,-11,-15,51,-28,42,-76,-93,1,-44, 
  /* [26][0][][] */ -28,-17,-30,-2,-98,-1,-18,57,-59,35,88,71,12,47,63,49, -107,-80,-69,69,17,-21,15,29,-84,38,-41,-19,59,1,84,-25, 32,-47,-42,-75,-40,0,127,-23,-11,-22,96,-51,-1,-21,37,9, 
  /* [27][0][][] */ 17,97,26,-14,39,5,-67,33,95,50,-73,-15,127,-51,-21,-66, -15,30,-10,-31,-2,-16,-13,-74,9,49,-31,-41,23,-35,-10,-24, -64,76,19,21,9,3,62,-73,-8,28,-19,-30,4,-31,34,-12, 
  /* [28][0][][] */ -20,20,-4,0,16,6,15,20,-53,64,-16,-10,-73,-38,83,29, -42,-55,-39,-15,33,13,-22,96,-127,-14,47,-46,-36,13,59,-44, -33,-57,-48,-10,29,24,36,63,-93,90,69,-75,-7,-23,-8,57, 
  /* [29][0][][] */ -8,-35,50,-25,49,9,-127,-59,-15,-7,-71,48,-24,-33,-14,27, 20,-71,84,52,-40,-52,-92,15,14,46,-29,-38,0,30,-15,36, 61,-28,26,34,62,43,-60,-8,49,-14,-16,-27,-66,-3,25,82, 
  /* [30][0][][] */ 5,6,44,-41,110,72,35,-69,-28,127,-13,-96,24,-100,31,-57, 30,66,11,9,91,-15,21,16,112,-16,67,-97,5,-95,-86,-33, 25,-11,40,17,96,8,-3,-74,83,27,41,-66,82,-90,-74,3, 
  /* [31][0][][] */ 79,-40,-19,44,-30,-44,-69,-52,-52,-79,-41,76,-43,-36,47,44, -24,-11,87,61,-25,-86,6,-71,-10,-100,-127,124,25,115,-95,-25, 39,-34,2,59,-37,-68,-3,-15,-46,27,-50,41,-21,80,-45,87, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant9_scale = { 32, { 0.0030604028142988682, 0.0031105675734579563, 0.0026384887751191854, 0.002880272688344121, 0.0037855412811040878, 0.0037097267340868711, 0.0020988793112337589, 0.0023391824215650558, 0.0028286662418395281, 0.0023207345511764288, 0.0027800509706139565, 0.0028001496102660894, 0.002235680352896452, 0.0029385180678218603, 0.0039025228470563889, 0.0032503872644156218, 0.0031668695155531168, 0.0030696694739162922, 0.0035817471798509359, 0.0024785215500742197, 0.0026407891418784857, 0.0030688229016959667, 0.0028427494689822197, 0.0028154323808848858, 0.0026928766164928675, 0.0024922788143157959, 0.0028877418953925371, 0.0036160631570965052, 0.0030248288530856371, 0.0030916694086045027, 0.0026813279837369919, 0.0024560820311307907, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[16] = { -2156, 4674, -700, -14938, -2798, 3200, 6465, 8804, 2437, 3928, 4918, -8045, 3747, 708, 9581, 5425, };
const TfArray<1, int> tensor_dimension10 = { 1, { 16 } };
const TfArray<16, float> quant10_scale = { 16, { 9.332459740107879e-06, 1.0420540093036834e-05, 8.9085160652757622e-06, 8.8890237748273648e-06, 8.154207534971647e-06, 9.4000060926191509e-06, 9.989760656026192e-06, 8.0676099969423376e-06, 1.0240280971629545e-05, 8.9745735749602318e-06, 8.3029044617433101e-06, 9.6148887678282335e-06, 8.8325114120380022e-06, 9.0565627033356577e-06, 1.0023632967204321e-05, 7.6926480687689036e-06, } };
const TfArray<16, int> quant10_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[16*1*3*32] = { 
  /* [0][0][][] */ -23,-17,-97,1,-91,-21,35,-87,6,-6,13,18,10,-14,7,-67,4,95,11,37,52,-80,-34,60,-15,70,-61,71,97,22,-94,35, -68,17,-9,-125,-127,-73,1,-74,51,61,53,-88,-81,-83,11,-58,-82,91,24,-25,33,-96,-42,-104,-12,-46,-31,65,-45,19,86,-88, 78,61,4,19,33,69,78,2,67,23,47,35,-73,-72,77,94,-23,-12,20,67,117,61,-1,38,-31,22,-42,-25,72,10,41,59, 
  /* [1][0][][] */ -89,-42,-86,-73,-25,-71,34,59,-75,60,52,59,37,-63,-25,-11,-39,27,-21,31,64,-25,16,49,-13,-26,41,-14,68,12,72,17, -127,-42,-48,-53,-58,-60,-69,-32,39,-35,-67,70,-58,-69,60,-46,-39,54,-31,-64,28,-28,-7,21,-14,-71,33,-15,40,-25,64,82, -50,-39,30,-71,-92,-17,-98,38,34,-99,15,4,33,-36,-63,-99,-41,-28,64,-55,52,55,38,51,-85,-67,26,82,9,15,-41,17, 
  /* [2][0][][] */ 56,-72,-84,16,-72,31,23,-68,30,52,67,-10,20,-62,-1,-55,-79,113,48,0,60,-4,5,25,73,92,-31,93,-73,52,12,-55, -73,-60,-100,-87,-121,-41,-106,-101,19,-65,38,83,49,-65,40,38,-61,127,61,-35,117,10,13,40,21,68,37,-25,54,-61,-18,-29, 70,-16,19,-51,29,-23,-18,-82,-55,-2,-57,63,-45,36,59,-50,-32,63,78,-67,85,-37,-8,35,70,81,19,71,-34,-10,50,-93, 
  /* [3][0][][] */ -62,11,59,52,61,17,-4,48,127,73,56,72,31,100,100,68,63,79,-56,-104,-29,-23,28,55,73,-78,-57,59,70,-16,35,-44, 7,63,23,50,27,-27,-6,96,106,106,53,26,-85,103,-71,-62,22,7,-99,-78,-5,51,69,55,-13,-78,-5,-95,35,-25,41,-107, -40,-30,-90,24,46,-45,-85,51,63,41,-81,80,-75,-37,8,-43,-59,-25,16,44,8,-72,-72,35,-76,-3,-67,-40,65,61,2,-55, 
  /* [4][0][][] */ 35,-40,-72,35,9,-80,59,-27,-66,-61,-21,-57,-69,-36,48,-71,-45,22,21,15,29,111,-17,113,40,29,19,-17,-32,48,-8,100, -71,-6,9,-49,-57,87,-29,-86,81,-88,-44,66,-18,-47,54,-105,-69,-21,57,37,-57,-44,-10,80,87,-47,123,21,2,-68,-22,103, -127,-99,-14,-42,-37,59,71,61,-39,-27,-18,-72,-30,69,-90,-57,18,-95,92,112,37,-59,16,119,10,1,102,9,109,33,-67,6, 
  /* [5][0][][] */ -34,-17,58,-12,14,-36,24,-23,-106,-34,-42,69,-9,-1,-60,-99,12,28,15,91,-118,49,15,-60,-60,-57,3,-20,2,77,62,61, -60,-63,56,2,-44,-56,40,-24,37,48,5,-23,23,37,-19,-69,61,-20,88,-19,-65,74,12,20,-31,-50,5,45,5,-2,48,48, 49,-7,-62,53,70,-15,16,48,-127,-6,4,2,56,-90,-23,42,-30,-38,72,91,-69,74,-33,-18,-82,57,59,-8,78,33,-72,3, 
  /* [6][0][][] */ 18,-24,-36,-51,-73,-77,-65,9,-14,6,-55,-36,-49,64,15,-17,30,-53,-92,-74,-45,44,-55,19,10,-35,-72,90,-28,95,-16,14, -94,-45,-57,24,-91,-103,41,-67,12,-75,-111,-58,24,-98,-30,-88,40,12,-33,2,-10,-87,-46,-76,-33,-18,-30,-61,-8,4,-76,13, -25,-19,50,3,-8,99,42,61,26,109,10,-22,1,-12,-10,78,63,84,-15,76,51,-29,6,79,33,46,11,116,1,126,127,98, 
  /* [7][0][][] */ 102,58,88,-44,4,82,81,-3,14,-23,24,-56,78,1,127,-18,82,9,77,62,-45,-16,-63,63,5,87,39,-57,-44,25,15,94, 53,-59,53,-70,107,72,34,-12,32,-49,-28,7,-29,-30,-76,18,25,36,-4,60,-102,46,-14,42,-95,-89,-96,54,-39,52,27,76, 107,-12,-110,65,80,52,-80,-89,-78,-79,-40,-56,18,43,24,-43,44,-110,-3,11,-62,-35,-91,-52,-115,-22,-50,-78,-8,38,51,-9, 
  /* [8][0][][] */ 1,-21,-41,-41,-44,-86,-84,18,-1,-63,-3,42,-2,-57,-47,62,-12,20,-5,72,45,61,-35,24,-21,90,81,98,56,90,70,40, -93,-71,-74,26,-102,-38,-14,6,1,-60,-78,-41,34,-68,-56,-7,-27,-21,-30,24,-53,12,-49,-94,-63,-23,59,75,-24,85,-4,35, -123,5,-68,-106,-63,-127,-36,40,77,37,12,23,-78,3,-36,51,8,65,4,0,30,43,-32,-10,-80,-32,15,59,-1,88,-85,-26, 
  /* [9][0][][] */ -85,63,90,114,4,-80,-78,15,-58,64,-70,13,-51,-61,-3,-127,25,7,-50,-49,-63,23,86,89,-38,-5,-60,82,-70,-41,89,0, -23,-60,98,29,110,-24,-10,-89,-83,-77,47,6,29,35,-71,-6,53,-64,40,53,40,95,-58,-17,-81,86,30,65,80,49,-76,-10, 63,-80,-16,36,49,-45,49,-10,59,-36,-23,-74,-71,-56,30,-90,-7,-38,89,12,25,-51,48,95,70,5,99,-51,17,37,-56,111, 
  /* [10][0][][] */ 81,-58,-93,66,33,-102,-98,58,-73,12,-26,-8,-75,-105,-110,-17,31,-84,-73,-49,-41,-56,-22,-62,-91,-74,16,59,-62,73,75,7, 77,-28,-80,81,20,-71,45,-55,-92,-40,-39,73,-71,-47,20,13,-95,-117,43,19,-126,-56,50,-28,-83,-28,111,-45,59,-6,55,37, 43,-24,93,94,112,-43,-20,122,48,4,-22,61,57,18,-26,105,56,46,70,127,63,90,-7,45,98,2,34,102,24,-42,89,96, 
  /* [11][0][][] */ -32,-91,-65,-41,-113,-124,-34,-35,18,-2,21,35,37,-76,55,70,24,85,-24,39,-6,-72,25,-50,65,-10,-46,-42,68,56,25,81, -84,-85,-74,6,-81,-111,-114,-52,2,-91,10,-26,-13,-66,45,34,-4,127,17,1,33,-2,-59,-50,7,3,-68,-11,-69,57,-61,22, 5,31,11,3,18,-70,12,50,-6,-47,48,44,-43,74,-33,-11,54,79,35,-28,-10,-36,88,46,-56,83,-33,45,22,7,70,40, 
  /* [12][0][][] */ -16,110,45,103,27,68,61,72,-37,-56,-63,-14,-35,15,-22,54,-3,-42,121,67,13,-31,6,-40,-24,83,95,21,64,6,78,121, 73,-30,74,76,-58,50,23,-7,-87,-16,-40,20,-74,48,71,45,-34,9,15,-28,-94,-34,60,-103,11,85,85,-47,20,56,66,-36, -32,-98,-80,-40,30,-107,-102,0,45,-2,-105,-81,-85,18,-102,1,9,-99,-35,11,-83,-33,-87,-127,-123,-27,16,-60,30,-58,28,-17, 
  /* [13][0][][] */ 72,79,44,18,78,127,96,39,76,113,-16,-91,-96,53,89,85,-46,22,-88,-57,-44,52,-5,-58,-53,-76,57,-3,-24,82,-45,40, 56,86,41,-26,41,28,113,-42,-17,29,4,-45,61,49,63,40,-67,-71,33,4,-21,58,-5,67,-92,-72,-58,81,81,-74,66,-26, -51,-77,-99,-23,-111,-56,10,-11,60,-60,-81,-35,-84,58,-23,75,15,-28,-89,-124,30,5,49,68,-61,-48,48,-9,-100,59,2,-73, 
  /* [14][0][][] */ 127,41,-9,-46,-54,13,-24,-18,89,3,42,30,-2,24,-19,-53,-43,33,56,-37,-64,15,101,64,54,71,41,-29,-40,62,-36,-8, 118,47,-29,65,68,46,38,-52,-45,-30,-85,-46,41,-77,-76,-74,-65,-54,-107,-32,-26,-16,51,7,64,70,-74,6,-72,17,-32,-31, -22,47,3,29,-52,-65,66,-38,43,-29,46,-5,13,49,6,60,9,-93,-81,-52,-71,-7,40,38,-64,34,68,-38,39,-74,25,-42, 
  /* [15][0][][] */ 39,62,47,71,-34,-58,-47,54,99,-1,85,21,12,121,107,-42,102,-61,-31,-30,35,-30,-65,73,18,-127,-55,-78,-44,-109,-1,-1, -14,69,-44,-16,51,48,80,30,-56,-44,-6,40,57,28,47,78,69,-18,40,73,106,71,48,65,-52,-23,-117,-5,-89,-47,-79,-57, 75,88,43,-32,-70,-28,127,-3,56,-12,117,35,82,86,95,40,14,56,3,-91,-67,6,-30,-65,-73,25,44,-93,-19,-1,4,-95, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 16,1,3,32 } };
const TfArray<16, float> quant11_scale = { 16, { 0.002389109693467617, 0.0026676582638174295, 0.0022805801127105951, 0.0022755900863558054, 0.0020874771289527416, 0.0024064015597105026, 0.0025573787279427052, 0.0020653081592172384, 0.0026215119287371635, 0.0022974908351898193, 0.0021255435422062874, 0.0024614115245640278, 0.0022611229214817286, 0.0023184800520539284, 0.0025660500396043062, 0.0019693179056048393, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,49,32 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,49,16 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0077314176596701145, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,49,1,16 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,25,16 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,25,32 } };
const TfArray<1, float> quant17_scale = { 1, { 0.012205176055431366, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,25,1,32 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,13,1,32 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,416 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.10218571871519089, } };
const TfArray<1, int> quant21_zero = { 1, { 10 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1568), (TfLiteIntArray*)&g0::tensor_dimension0, 1568, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1664, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 1568, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1568), (TfLiteIntArray*)&g0::tensor_dimension13, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_828917_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_828917_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_828917_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_828917_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_828917_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
