// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBIdBSaVKSNaA64Y7rfnucOdEI9K71m4_M",
    authDomain: "safeandsound-ea1e1.firebaseapp.com",
    projectId: "safeandsound-ea1e1",
    storageBucket: "safeandsound-ea1e1.appspot.com",
    messagingSenderId: "920384330641",
    appId: "1:920384330641:web:9c7923d1459c0bb95e9830",
    databaseURL: "https://safeandsound-ea1e1-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBIdBSaVKSNaA64Y7rfnucOdEI9K71m4_M",
    authDomain: "safeandsound-ea1e1.firebaseapp.com",
    projectId: "safeandsound-ea1e1",
    storageBucket: "safeandsound-ea1e1.appspot.com",
    messagingSenderId: "920384330641",
    appId: "1:920384330641:web:d88782debaf033255e9830",
    databaseURL: "https://safeandsound-ea1e1-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDbx6Xuwv_RtFrWM8IlCkViLg2zJcfCVKs",
    projectId: "safeandsound-ea1e1",
    appId: "1:920384330641:android:e4842a61843567ca5e9830",
    messagingSenderId: "920384330641",
    storageBucket: "safeandsound-ea1e1.appspot.com",
    databaseURL: "https://safeandsound-ea1e1-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB7cD7SIrGXi3Sbo5U55mYJlP0pgw_xH_g",
    projectId: "safeandsound-ea1e1",
    appId: "1:920384330641:ios:54f97ccbdc3771a75e9830",
    messagingSenderId: "920384330641",
    storageBucket: "safeandsound-ea1e1.appspot.com",
    iosBundleId: "com.example.app",
    databaseURL: "https://safeandsound-ea1e1-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB7cD7SIrGXi3Sbo5U55mYJlP0pgw_xH_g",
    projectId: "safeandsound-ea1e1",
    appId: "1:920384330641:ios:54f97ccbdc3771a75e9830",
    messagingSenderId: "920384330641",
    storageBucket: "safeandsound-ea1e1.appspot.com",
    iosBundleId: "com.example.app",
    databaseURL: "https://safeandsound-ea1e1-default-rtdb.firebaseio.com/",
  );
}
